### PR TITLE
Objective-C fixes

### PR DESCRIPTION
**Pull request by brightsider**
This change is [Reviewable](https://reviewable.io/reviews/alexruperez/arfacebooksharekitactivity/3)

### CODE REVIEW

**Comment by alexruperez** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/alexruperez/arfacebooksharekitactivity/3)*

**Comment by alexruperez** [comment]
Thanks @brightsider! 😃

**Comment by alexruperez** [comment]
@brightsider your changes and everything in Swift 4, uploaded to CocoaPods with release version 1.2

**Comment by brightsider** [comment]
I'm don't fix deprecated open override class func initialize()

**Comment by alexruperez** [comment]
I make it [optional](https://github.com/alexruperez/ARFacebookShareKitActivity#easter-egg)

**Pull request merged**
